(function(){'use strict';
const D=globalThis.DL, KEY='doce-lembranca-v1';
let data=load(), route=location.hash.slice(1)||'home';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>n==null?'A definir':Number(n).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));return x?D.validate(x):D.seed()}catch(e){return D.seed()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function toast(s){const el=$('#toast');el.textContent=s;el.style.display='block';setTimeout(()=>el.style.display='none',2800)}
function nav(){const items=[['home','⌂','Início'],['orders','◷','Pedidos'],['recipes','◌','Receitas'],['production','♨','Produção'],['more','⋯','Mais']];$('#nav').innerHTML=items.map(x=>`<a class="${route===x[0]?'active':''}" href="#${x[0]}"><span class="ico">${x[1]}</span>${x[2]}</a>`).join('')}
function frame(){nav();$('#breadcrumb').textContent={home:'Seu ateliê',orders:'Pedidos',recipes:'Receitas',production:'Produção',more:'Mais'}[route]||'Seu ateliê';$('#app').innerHTML=views[route]?views[route]():views.home();bind();}
function btn(label,action,cls=''){return `<button class="${cls}" data-action="${action}">${label}</button>`}
function empty(text,action,label){return `<div class="empty"><div class="symbol">♡</div><p>${text}</p>${action?btn(label,action,'primary'):''}</div>`}
function status(o){return `<span class="pill ${o.status==='Pronto'?'green':''}">${esc(o.status)}</span>`}
function productOptions(){return data.products.filter(p=>p.active).map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('')}
const views={
 home(){const upcoming=data.orders.filter(o=>!['Entregue','Cancelado'].includes(o.status)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const n=D.needs(data);return `<div class="title-row"><div><div class="eyebrow">Bom ter você aqui</div><h1>Uma cozinha que respira.</h1><p class="muted">Pedidos, preparos e números no lugar certo.</p></div>${btn('+ Novo pedido','new-order','primary')}</div><div class="quick"><a href="#orders"><span>◷</span>Pedidos</a><a href="#recipes"><span>◌</span>Receitas</a><a href="#production"><span>♨</span>Produção</a><a href="#more"><span>⌂</span>Compras</a><a href="#more"><span>◒</span>Financeiro</a><a href="#more"><span>＋</span>Produtos</a></div><div class="columns"><section class="panel"><div class="section-row"><h2>Próximos pedidos</h2><a href="#orders">Ver todos</a></div>${upcoming.length?upcoming.slice(0,5).map(orderRow).join(''):empty('Quando houver pedidos, eles aparecem organizados por data e horário.','new-order','Criar pedido')}</section><aside class="panel"><h2>Hoje na cozinha</h2><p><b>${data.preps.filter(p=>p.remaining>0).length}</b> preparos disponíveis</p><p><b>${n.missing.length}</b> pendências de cadastro</p><div class="notice">Os valores ainda não confirmados continuam como <b>A definir</b>.</div></aside></div>`},
 orders(){const list=[...data.orders].sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));return `<div class="title-row"><div><div class="eyebrow">A agenda da sua produção</div><h1>Pedidos</h1></div>${btn('+ Novo pedido','new-order','primary')}</div><div class="panel">${list.length?list.map(orderRow).join(''):empty('Cadastre o primeiro pedido para começar.','new-order','Novo pedido')}</div>`},
 recipes(){return `<div class="title-row"><div><div class="eyebrow">O que dá sabor ao seu trabalho</div><h1>Receitas</h1></div>${btn('+ Nova receita','new-recipe','primary')}</div><div class="grid">${data.recipes.map(r=>`<article class="card"><div class="recipe-mark">✦</div><div class="eyebrow">${esc(r.category||'Receita')}</div><h3>${esc(r.name)}</h3><p class="muted">Rendimento: ${r.yield==null?'A definir':r.yield+' '+r.unit}</p><p class="muted">${r.ingredients.length} ingrediente(s) · Versão ${r.version}</p></article>`).join('')||empty('As receitas internas ficam aqui, separadas dos produtos de venda.','new-recipe','Cadastrar receita')}</div>`},
 production(){const available=data.preps.filter(p=>p.remaining>0);return `<div class="title-row"><div><div class="eyebrow">Da bancada para a entrega</div><h1>Produção</h1></div>${btn('+ Registrar preparo','new-prep','primary')}</div><div class="columns"><section class="panel"><h2>A fazer</h2>${data.orders.filter(o=>['Confirmado','Em produção'].includes(o.status)&&!o.consumed).map(o=>`<div class="order-row"><div class="grow"><h3>${esc(o.customer.name)} ${status(o)}</h3><p>${esc(o.date)} às ${esc(o.time)} · ${o.lines.map(l=>l.quantity+'× '+esc(l.name)).join(', ')}</p></div>${btn('Marcar pronto','finish:'+o.id)}</div>`).join('')||empty('Pedidos confirmados aparecerão aqui.')}</section><section class="panel"><h2>Preparos disponíveis</h2>${available.map(p=>`<div class="order-row"><div class="grow"><h3>${esc(p.name)}</h3><p>${p.remaining} ${p.unit} disponíveis · ${p.date}</p></div></div>`).join('')||empty('Registre um preparo para formar seu estoque de produção.','new-prep','Registrar preparo')}</section></div>`},
 more(){return `<div class="title-row"><div><div class="eyebrow">Organização por trás do doce</div><h1>Mais</h1></div></div><div class="grid"><article class="card"><h3>Produtos e preços</h3><p class="muted">O preço usado no pedido é sempre o preço de venda cadastrado.</p>${btn('Gerenciar produtos','products')}</article><article class="card"><h3>Compras e estoque</h3><p class="muted">Registre compras reais e mantenha a contagem atualizada.</p>${btn('Abrir compras','purchases')}</article><article class="card"><h3>Financeiro</h3><p class="muted">Vendido, recebido, a receber, despesas e resultado.</p>${btn('Abrir financeiro','finance')}</article><article class="card"><h3>Clientes</h3><p class="muted">Cadastros, histórico e pedidos repetidos.</p>${btn('Abrir clientes','clients')}</article><article class="card"><h3>Backup</h3><p class="muted">Seus dados ficam neste navegador. Exporte uma cópia regularmente.</p>${btn('Exportar backup','export','primary')} ${btn('Importar backup','import')}</article></div>`}
};
function orderRow(o){return `<div class="order-row"><div class="datebox"><b>${esc(o.date.slice(8,10))}</b><span>${esc(o.date.slice(5,7))}/${esc(o.date.slice(0,4))}</span></div><div class="grow"><h3>${esc(o.customer.name)} ${status(o)}</h3><p>${esc(o.time)} · ${o.mode} · ${o.lines.map(l=>l.quantity+'× '+esc(l.name)).join(', ')}</p><p>${money(D.total(o))} · recebido ${money(D.paid(o))}</p></div>${btn('Abrir','view-order:'+o.id)}</div>`}
function modal(title,body){const m=$('#modal');m.innerHTML=`<button class="close" data-action="close">×</button><h2>${title}</h2>${body}`;m.showModal();bind()}
function formActions(){return `<div class="form-actions"><button type="button" data-action="close">Cancelar</button><button class="primary" type="submit">Salvar</button></div>`}
function openOrder(){modal('Novo pedido',`<form data-form="order"><div class="formgrid"><div><label>Cliente<select name="client" required>${data.clients.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></label></div><div><label>Status<select name="status"><option>Orçamento</option><option>Confirmado</option></select></label></div><div><label>Data de entrega/retirada<input name="date" type="date" required value="${D.today()}"></label></div><div><label>Horário<input name="time" type="time" required></label></div><div><label>Modalidade<select name="mode"><option>Retirada</option><option>Entrega</option></select></label></div><div><label>Taxa de entrega<input name="fee" type="number" step="0.01" value="0"></label></div><div class="wide"><label>Endereço (obrigatório para entrega)<input name="address"></label></div><div class="wide"><label>Produto<select name="product" required>${productOptions()}</select></label></div><div><label>Quantidade<input name="quantity" type="number" min="1" step="1" value="1"></label></div><div><label>Sinal recebido<input name="deposit" type="number" min="0" step="0.01" value="0"></label></div><div class="wide"><label>Observações<textarea name="notes"></textarea></label></div></div>${formActions()}</form>`)}
function openRecipe(){modal('Nova receita',`<form data-form="recipe"><label>Nome<input name="name" required></label><label>Categoria<input name="category" value="Brigadeiros"></label><label>Unidade<select name="unit"><option>g</option><option>ml</option><option>un</option></select></label><label>Rendimento real histórico<input name="yield" type="number" step="0.01" placeholder="Deixe vazio se A definir"></label><label>Modo de preparo<textarea name="method"></textarea></label>${formActions()}</form>`)}
function openPrep(){modal('Registrar preparo',`<form data-form="prep"><label>Receita<select name="recipe" required>${data.recipes.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label>Número de receitas<input name="batches" type="number" min="0.01" step="0.01" value="1"></label><label>Rendimento real produzido<input name="produced" type="number" min="0.01" step="0.01" required></label><label>Conservação e validade<textarea name="conservation"></textarea></label>${formActions()}</form>`)}
function showOrder(id){const o=data.orders.find(x=>x.id===id);if(!o)return;modal('Pedido #'+o.number,`<p><b>${esc(o.customer.name)}</b><br>${esc(o.date)} às ${esc(o.time)} · ${o.mode}</p><table><tbody>${o.lines.map(l=>`<tr><td>${l.quantity}× ${esc(l.name)}</td><td>${money(l.price*l.quantity)}</td></tr>`).join('')}<tr><th>Total</th><th>${money(D.total(o))}</th></tr><tr><td>Recebido</td><td>${money(D.paid(o))}</td></tr></tbody></table><p>${esc(o.notes)}</p><div class="actions">${btn('Registrar pagamento','pay:'+id)} ${o.status==='Confirmado'?btn('Abrir produção','production'):''} ${btn('Imprimir','print:'+id)}</div>`)}
function openPayment(id){const o=data.orders.find(x=>x.id===id);modal('Registrar pagamento',`<p>Saldo: <b>${money(D.total(o)-D.paid(o))}</b></p><form data-form="payment" data-id="${id}"><label>Valor<input name="amount" type="number" step="0.01" max="${D.total(o)-D.paid(o)}" required></label><label>Data real<input name="date" type="date" value="${D.today()}" required></label><label>Forma de pagamento<input name="method" placeholder="Pix, dinheiro..."></label>${formActions()}</form>`)}
function finance(){const sold=data.orders.reduce((s,o)=>s+D.total(o),0),received=data.orders.reduce((s,o)=>s+D.paid(o),0),expenses=data.expenses.reduce((s,e)=>s+e.amount,0);modal('Financeiro',`<div class="stats"><div class="stat"><span>Vendido</span><strong>${money(sold)}</strong></div><div class="stat"><span>Recebido</span><strong>${money(received)}</strong></div><div class="stat"><span>A receber</span><strong>${money(sold-received)}</strong></div><div class="stat"><span>Despesas</span><strong>${money(expenses)}</strong></div><div class="stat"><span>Resultado</span><strong>${money(received-expenses)}</strong></div></div><p class="muted">Apenas movimentações da Doce Lembrança entram neste resumo.</p>`)}
function products(){modal('Produtos e preços',`<form data-form="product"><label>Nome do produto<input name="name" required placeholder="Ex.: Brigadeiro Festa 16 g"></label><label>Preço de venda<input name="price" type="number" step="0.01" required></label><label class="check"><input name="active" type="checkbox" checked> Disponível para encomenda</label>${formActions()}</form><hr><table><tbody>${data.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${money(p.price)}</td><td>${p.active?'Ativo':'Inativo'}</td></tr>`).join('')||'<tr><td>Ainda não há produtos cadastrados.</td></tr>'}</tbody></table>`)}
function clients(){modal('Clientes',`<form data-form="client"><label>Nome completo<input name="name" required></label><label>Telefone<input name="phone"></label><label>Endereço<input name="address"></label>${formActions()}</form><hr>${data.clients.map(c=>`<p><b>${esc(c.name)}</b><br><span class="muted">${esc(c.phone||'Sem telefone')}</span></p>`).join('')}`)}
function purchases(){modal('Compras e estoque',`<p class="muted">A lista automática considera pedidos confirmados, preparos disponíveis e estoque. O registro abaixo atualiza a contagem.</p><form data-form="purchase"><label>Item<select name="item">${data.inventory.map(i=>`<option value="${i.id}">${esc(i.name)} (${i.quantity==null?'contagem pendente':i.quantity+' '+i.unit})</option>`).join('')}</select></label><label>Quantidade<input name="quantity" type="number" step="0.01" required></label><label>Total pago<input name="amount" type="number" step="0.01" required></label><label>Data<input name="date" type="date" value="${D.today()}" required></label>${formActions()}</form>`)}
function bind(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelectorAll('form').forEach(f=>f.onsubmit=submit)}
function act(a){if(a==='close')return $('#modal').close();if(a==='new-order')return openOrder();if(a==='new-recipe')return openRecipe();if(a==='new-prep')return openPrep();if(a==='products')return products();if(a==='clients')return clients();if(a==='purchases')return purchases();if(a==='finance')return finance();if(a==='export'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='doce-lembranca-backup.json';a.click();URL.revokeObjectURL(u);return toast('Backup exportado.')}if(a==='import'){const i=document.createElement('input');i.type='file';i.accept='.json';i.onchange=()=>{const r=new FileReader();r.onload=()=>{try{data=D.validate(JSON.parse(r.result));save();frame();toast('Backup importado.')}catch(e){toast(e.message)}};r.readAsText(i.files[0])};i.click();return}if(a.startsWith('view-order:'))return showOrder(a.split(':')[1]);if(a.startsWith('pay:'))return openPayment(a.split(':')[1]);if(a.startsWith('finish:')){try{D.finish(data,data.orders.find(o=>o.id===a.split(':')[1]));save();frame();toast('Produção concluída.')}catch(e){toast(e.message)}return}if(a.startsWith('print:')){const o=data.orders.find(o=>o.id===a.split(':')[1]);$('#print-area').innerHTML=`<h1>Doce Lembrança — Pedido #${o.number}</h1><p>Cliente: ${esc(o.customer.name)}\nData: ${o.date} às ${o.time}\nModalidade: ${o.mode}</p><table>${o.lines.map(l=>`<tr><td>${l.quantity}× ${esc(l.name)}</td><td>${money(l.price*l.quantity)}</td></tr>`).join('')}<tr><th>Total</th><th>${money(D.total(o))}</th></tr></table>`;window.print();return}}
function submit(ev){ev.preventDefault();const f=ev.currentTarget,v=Object.fromEntries(new FormData(f));try{if(f.dataset.form==='order'){const p=data.products.find(x=>x.id===v.product);D.order(data,{client:v.client,date:v.date,time:v.time,mode:v.mode,address:v.address,fee:v.fee,notes:v.notes,status:v.status,deposit:v.deposit,lines:[{product:p.id,quantity:v.quantity}]})}else if(f.dataset.form==='recipe'){data.recipes.push({id:D.id(),name:v.name,category:v.category,unit:v.unit,yield:v.yield?Number(v.yield):null,coating:null,method:v.method,conservation:'',validity:null,condition:'',version:1,ingredients:[],history:[]})}else if(f.dataset.form==='prep')D.prepare(data,v);else if(f.dataset.form==='payment')D.payment(data,data.orders.find(o=>o.id===f.dataset.id),v.amount,v.date,v.method||'Não informado');else if(f.dataset.form==='product')data.products.push({id:D.id(),name:v.name,price:Number(v.price),active:f.querySelector('[name=active]').checked,components:[]});else if(f.dataset.form==='client')data.clients.push({id:D.id(),name:v.name,phone:v.phone,address:v.address,notes:''});else if(f.dataset.form==='purchase')D.purchase(data,v.item,v.quantity,v.amount,v.date);save();$('#modal').close();frame();toast('Salvo com sucesso.')}catch(e){const old=f.querySelector('.error');if(old)old.remove();const p=document.createElement('p');p.className='error';p.textContent=e.message;p.after(f.querySelector('label'));f.prepend(p)}}
const viewsMore=views.more;window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'home';frame()});$('#mode').onclick=()=>{data=D.demo();save();frame();toast('Modo de teste ativado. Os dados são demonstração.')};frame();
})();
