(function(root){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x)),id=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),today=()=>new Date().toLocaleDateString('en-CA');
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
function num(x,label,min=0){const n=Number(x);if(x===null||x===''||!Number.isFinite(n)||n<min)throw Error(label+' inválido.');return n;}
function seed(){return {version:1,company:{name:'Doce Lembrança',city:'Maringá/PR',document:'',address:'',phone:'',terms:'',termsVersion:1},clients:[{id:'br',name:'BR Pastel',phone:'',address:'',notes:'Cliente citado na conversa: 60 doces semanais. Datas, produtos e preços a definir.'}],inventory:['Leite','Leite condensado','Creme de leite','Gemas peneiradas','Amido de milho','Baunilha'].map((name,i)=>({id:'i'+i,name,unit:['ml','g','g','un','g','gotas'][i],category:'Ingredientes',quantity:null,minimum:null,reference:null})),recipes:[{id:'creme',name:'Creme Branco para Tortalete',category:'Preparos internos',unit:'g',yield:null,coating:null,method:'Modo de preparo a recuperar da ficha original.',conservation:'',validity:null,condition:'',version:1,ingredients:[{item:'i0',quantity:1000},{item:'i1',quantity:395},{item:'i2',quantity:200},{item:'i3',quantity:4},{item:'i4',quantity:50},{item:'i5',quantity:null}],history:[],source:'Conversa Continuar aplicativo Doce Lembrança; fórmula recuperada. Baunilha: gotas, quantidade não informada.'}],products:[],orders:[],preps:[],purchases:[],expenses:[],movements:[],sanitary:{enabled:false,lots:[],temperatures:[],cleaning:[],documents:[]}};}
function demo(){let d=seed();d.clients=[{id:'demo-client',name:'Cliente de teste',phone:'',address:'',notes:'DEMONSTRAÇÃO'}];d.inventory=[{id:'demo-item',name:'Ingrediente de teste',unit:'g',category:'Ingredientes',quantity:1000,minimum:100,reference:0.02}];d.recipes=[{id:'demo-recipe',name:'Massa de teste',category:'Brigadeiros',unit:'g',yield:500,coating:0,ingredients:[{item:'demo-item',quantity:500}],version:1,history:[],method:'Somente demonstração.',conservation:'',validity:null}];d.products=[{id:'demo-product',name:'Doce de teste • 16 g',size:'16',price:3,active:true,components:[{kind:'recipe',item:'demo-recipe',quantity:16}]}];return d;}
function total(o){return round(o.lines.reduce((s,l)=>s+l.price*l.quantity,0)+o.fee);}
function paid(o){return round(o.payments.reduce((s,p)=>s+p.amount,0));}
function order(d,v){if(!d.clients.some(c=>c.id===v.client))throw Error('Selecione um cliente.');if(!v.date||!v.time)throw Error('Informe data e horário.');if(!v.lines.length)throw Error('Adicione ao menos um produto.');const lines=v.lines.map(l=>{const p=d.products.find(p=>p.id===l.product);if(!p||!p.active)throw Error('Produto indisponível.');const price=num(p.price,'Preço de '+p.name),quantity=num(l.quantity,'Quantidade',1);if(!Number.isInteger(quantity))throw Error('Quantidade deve ser inteira.');return {product:p.id,name:p.name,price,quantity,components:clone(p.components),recipes:p.components.filter(c=>c.kind==='recipe').map(c=>clone(d.recipes.find(r=>r.id===c.item)))};});const o={id:id(),number:d.orders.length+1,client:v.client,customer:clone(d.clients.find(c=>c.id===v.client)),date:v.date,time:v.time,mode:v.mode,address:v.address||'',fee:v.mode==='Entrega'?num(v.fee,'Taxa'):0,notes:v.notes||'',status:v.status||'Orçamento',lines,payments:[],history:[],created:today(),consumed:false};if(o.mode==='Entrega'&&!o.address.trim())throw Error('Informe o endereço da entrega.');const deposit=num(v.deposit||0,'Sinal');if(deposit>total(o))throw Error('Sinal maior que o total.');if(deposit)o.payments.push({id:id(),amount:deposit,date:v.paymentDate||today(),method:v.method||'Não informado'});d.orders.push(o);return o;}
function payment(o,amount,date,method){amount=num(amount,'Valor',0.01);if(amount>round(total(o)-paid(o)))throw Error('Pagamento maior que o saldo.');if(!date)throw Error('Informe a data.');o.payments.push({id:id(),amount,date,method});}
function recipeYield(d,r){const a=d.preps.filter(p=>p.recipe===r.id&&p.recipeVersion===r.version);return a.length?a.reduce((s,p)=>s+p.produced/p.batches,0)/a.length:r.yield;}
function recipeCost(d,r){if(!r.ingredients.length)return null;let sum=0;for(const c of r.ingredients){const i=d.inventory.find(i=>i.id===c.item);if(!i||i.reference==null||c.quantity==null)return null;sum+=i.reference*c.quantity;}return sum;}
function productCost(d,p){if(!p.components.length)return null;let sum=0;for(const c of p.components){if(c.kind==='recipe'){const r=d.recipes.find(r=>r.id===c.item),y=r&&recipeYield(d,r),cost=r&&recipeCost(d,r);if(!y||cost==null)return null;sum+=cost/y*c.quantity;}else{const i=d.inventory.find(i=>i.id===c.item);if(!i||i.reference==null)return null;sum+=i.reference*c.quantity;}}return sum;}
function needs(d,orders=d.orders.filter(o=>['Confirmado','Em produção'].includes(o.status)&&!o.consumed)){const stock={},prep={},missing=[],raw={},recipes={};for(const p of d.preps){const key=p.recipe+'@'+p.recipeVersion;prep[key]=(prep[key]||0)+p.remaining;}for(const o of orders)for(const l of o.lines){if(!l.components.length){missing.push('Composição de '+l.name);continue;}for(const c of l.components){const q=c.quantity*l.quantity;if(c.kind==='item'){raw[c.item]=(raw[c.item]||0)+q;continue;}const r=l.recipes.find(r=>r?.id===c.item);if(!r){missing.push('Receita de '+l.name);continue;}const key=r.id+'@'+r.version,used=Math.min(prep[key]||0,q);prep[key]=(prep[key]||0)-used;const deficit=q-used;if(!deficit)continue;recipes[key]=(recipes[key]||0)+deficit;const y=recipeYield(d,r);if(!y||!r.ingredients.length){missing.push('Rendimento/ingredientes de '+r.name);continue;}for(const ing of r.ingredients){if(ing.quantity==null){missing.push('Quantidade de ingrediente em '+r.name);continue;}raw[ing.item]=(raw[ing.item]||0)+ing.quantity*deficit/y;}}}for(const i of d.inventory){if(i.quantity==null){if(raw[i.id]||i.minimum!=null)missing.push('Contagem de '+i.name);continue;}stock[i.id]=Math.max(0,(raw[i.id]||0)-i.quantity,(i.minimum??0)-i.quantity);}return {raw,stock,recipes,missing:[...new Set(missing)]};}
function purchase(d,item,quantity,amount,date){const i=d.inventory.find(i=>i.id===item);if(!i)throw Error('Escolha o item.');if(i.quantity==null)throw Error('Conte o estoque atual antes de registrar a compra.');quantity=num(quantity,'Quantidade',0.0001);amount=num(amount,'Total pago');if(!date)throw Error('Informe a data.');i.quantity+=quantity;const p={id:id(),item,quantity,amount,date};d.purchases.push(p);d.movements.push({id:id(),item,quantity,type:'Compra',date});return p;}
function prepare(d,v){const r=d.recipes.find(r=>r.id===v.recipe);if(!r||!r.ingredients.length)throw Error('Cadastre ingredientes da receita.');const batches=num(v.batches,'Número de receitas',0.0001),produced=num(v.produced,'Rendimento real',0.0001);for(const c of r.ingredients){const i=d.inventory.find(i=>i.id===c.item);if(c.quantity==null||!i||i.quantity==null)throw Error('Complete quantidades e estoque de todos os ingredientes.');if(i.quantity<c.quantity*batches)throw Error('Estoque insuficiente: '+i.name);}for(const c of r.ingredients){const q=c.quantity*batches;d.inventory.find(i=>i.id===c.item).quantity-=q;d.movements.push({id:id(),item:c.item,quantity:-q,type:'Produção',date:today()});}d.preps.push({id:id(),recipe:r.id,recipeVersion:r.version,name:r.name,unit:r.unit,produced,remaining:produced,batches,conservation:v.conservation,date:today(),history:[],lot:null,expires:null});}
function finish(d,o){if(o.consumed)throw Error('Este pedido já teve o consumo registrado.');const preps=clone(d.preps),inventory=clone(d.inventory);for(const l of o.lines){if(!l.components.length)throw Error('Complete a composição de '+l.name);for(const c of l.components){let remaining=c.quantity*l.quantity;if(c.kind==='item'){const i=inventory.find(i=>i.id===c.item);if(!i||i.quantity==null||i.quantity<remaining)throw Error('Estoque insuficiente para '+l.name);i.quantity-=remaining;}else{const r=l.recipes.find(r=>r?.id===c.item);for(const p of preps.filter(p=>p.recipe===c.item&&p.recipeVersion===r?.version)){const used=Math.min(remaining,p.remaining);p.remaining-=used;remaining-=used;}if(remaining>0.000001)throw Error('Registre o preparo necessário para '+l.name+' (versão da receita usada no pedido).');}}}d.preps=preps;d.inventory=inventory;o.consumed=true;o.status='Pronto';o.history.push({date:new Date().toISOString(),text:'Produção concluída; ingredientes diretos e preparos consumidos.'});}
function validate(d){if(!d||d.version!==1||!d.company)throw Error('Backup incompatível.');for(const key of ['clients','inventory','recipes','products','orders','preps','purchases','expenses','movements']){if(!Array.isArray(d[key]))throw Error('Backup incompleto: '+key);if(d[key].some(x=>!x||typeof x.id!=='string'))throw Error('Registros inválidos.');if(new Set(d[key].map(x=>x.id)).size!==d[key].length)throw Error('IDs duplicados.');}for(const o of d.orders){if(!Array.isArray(o.lines)||!Array.isArray(o.payments)||!Number.isFinite(total(o)))throw Error('Pedido inválido.');}return d;}
root.DL={seed,demo,clone,id,today,round,num,total,paid,order,payment,recipeYield,recipeCost,productCost,needs,purchase,prepare,finish,validate};if(typeof module!=='undefined')module.exports=root.DL;
})(globalThis);
